name: ReBarDxe EDK2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  TARGET: RELEASE
  TARGET_ARCH: X64
  TOOL_CHAIN_TAG: VS2019

jobs:
  rebardxe-windows:
    runs-on: windows-2019

    steps:
    - uses: actions/setup-python@v4.3.0
    - run: pip install pefile

    # save nasm
    - name: cache nasm
      id: cache-nasm
      uses: actions/cache@v3
      with:
        path: C:\nasm
        key: nasm-path

    # edk2's setup script checks for nasm only at 'C:\nasm' so install it there
    - name: install nasm
      if: steps.cache-nasm.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        md C:\nasm
        Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip" -OutFile "C:\nasm\nasm.zip"
        cd C:\nasm
        7z e nasm.zip
      
    - name: Download edk2
      uses: actions/checkout@v3
      with:
        repository: 'tianocore/edk2'
        ref: 'edk2-stable202208'
        submodules: 'recursive'
        
    - name: Download RebarUEFI
      uses: actions/checkout@v3
      with:
        path: '.\ReBarUEFI\'

    - name: Setup EDK2
      run: .\edksetup.bat Rebuild
      
    - name: Build RebarDxe
      run: .\ReBarUEFI\.github\workflows\buildffs.bat

    - name: Upload ReBarDxe artifact
      uses: actions/upload-artifact@master
      with:
        name: ReBarDxe
        path: ${{github.workspace}}/Build/ReBarUEFI/RELEASE_VS2019/X64/ReBarDxe.ffs
  
  
  rebardxe-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/setup-python@v4.3.0
    - run: pip install pefile

    - name: Download edk2
      uses: actions/checkout@v3
      with:
        repository: 'tianocore/edk2'
        ref: 'edk2-stable202208'
        submodules: 'recursive'
        
    - name: Download RebarUEFI
      uses: actions/checkout@v3
      with:
        path: './ReBarUEFI/'

    - name: Setup EDK2
      run: ./edksetup.sh Rebuild
      
    - name: Build RebarDxe
      run: ./ReBarUEFI/.github/workflows/buildffs.sh

    - name: Upload ReBarDxe artifact
      uses: actions/upload-artifact@master
      with:
        name: ReBarDxe
        path: ${{github.workspace}}/Build/ReBarUEFI/RELEASE_VS2019/X64/ReBarDxe.ffs
